#!/usr/bin/python
# This is an attempt to create a FreeCad macro to create all the parts for my CNC router.






# Rough Draft

#load part module

#create a new document

#Do all the algebra calcs for the parts

#create an offset vector variable
	#firstoffset
	#secondoffset


#For Each Part
	# Do the math.

	#Almost all of my pieces are made in points from 0,0 to width(x),height(y). This is not always true.
	#Note, my script assumes width,height is X,Y. FreeCad assumes Length, Width, Height is X,Y,Z.
	#the makebox function works on length, width, height. I can abandon points, but...
	#some of the pieces extend negative X direction.
	#I need to calculate length and width for each part, even though it's already done for most?
	#I need to adjust offsets differently for the part and the holes and slideys?
	#if lower corner is -10mm, makebox starts it at 0
	#hole was supposed to be at -5, now needs to be at 5. 
	#So, I think I will simply readjust the offset by the abs(negative amount)
	#This means I need two offset variables. One inside the part, one for the part. 

	#OR!
	#I can just make the part, shift it over to match the script I have already done,
	#then all my holes and slideys match up fine... THEN offset the whole thing. It means an extra
	#move for the initial block... but it also means not having offsets all over the stupid place.
	#go with this......



	#create size, location, etc variables
		#size   will contain length(X), width(Y, what I think of as height), and MDF size for height.
			#changed my mind, this only obfuscates what I'm doing. just calculate 'em.
		#holes   contains [locations, radii, MDF size] of all the bolt holes to be drilled in the part
		#slideys   contains [lower left, upper right, and MDF] of all the slidey holes to be cut.

	#create a box representing the piece of MDF, correctly sized, at offset.
		#use offset and size

	#create cylinders representing the holes to be drilled, properly placed, with offset.
		#use locations, radii, and MDF in holes variable


	#create boxes representing the slidey holes to be cut, properly placed, with offset.
		#use locations in slideys variable

	#subtract all of the cylinders and boxes from the first piece. recompute the shape
		#I deeply suspect I should do this after each part.

	#move the part
		#I was going to create everything offset.
		#It seems much simpler to create it all and then move it.
		#That's how all the examples are done. When in Rome....
		#Move the final assembled part out of the way


#show it on the screen. Think this is done by the recompute.

#save it






#slightly less rough draft, more proof of concept. 
#Make a part with a hole in it. 10x10mm, 2mm diameter hole in center. Move it 10mm down X.

#load part module
import FreeCAD, Part, Draft
#from FreeCAD import Base   #why the difference?


#create a new document
doc=App.newDocument()

#Do all the algebra calcs for the parts
MDF = 19.05
radius = 1
lengthx = 10
widthy = 10
height = MDF

#create an offset vector variable
offset = FreeCAD.Vector(10,0,0)

	#create a box representing the piece of MDF, correctly sized, at offset.
testfixture = Part.makeBox(lengthx,widthy,MDF) #works
#testfixture2 = Part.makeBox(lengthx,widthy,MDF,Base.Vector(15,0,0)) #also works, can do offset at creation

#example from FreeCAD website
#import Part
#mycube = Part.makeBox(2,2,2)
#Part.show(mycube)

	#create cylinders representing the holes to be drilled, properly placed, with offset.
#hole=Part.makeCylinder(holes[1],MDF)
hole=Part.makeCylinder(radius,MDF,FreeCAD.Vector(5,5,0))

	#create boxes representing the slidey holes to be cut, properly placed, with offset.
		#use offset, locations

	#subtract all of the cylinders and boxes from the first piece. recompute the shape
		#I deeply suspect I should do this after each part.
		#Draft.cut(first,second) #yeah, that doesn't work either. 

		#Cribbed from the internet...
		#Make the head
		#head = Part.makeCylinder(headRadius, headLength)
		#Make the hex (requires the regPolygon function imported above)
		#hex = regPolygon(sides = 6, radius = hexSize / 2.0, extrude = headLength / 2.0, Z_offset = headLength /2.0)
		#cut the hex from the head
		#head = head.cut(hex)

testfixture = testfixture.cut(hole)

		#doc.recompute() #Updates the document. also prepares the visual of the new part. doesn't actually seem to work though... damnit.
#Try this
#App.ActiveDocument.recompute()
#Gui.activeDocument().activeView().viewAxometric()
#Gui.SendMsgToActiveView("ViewFit")

testfixture.translate(FreeCAD.Vector(5,0,0))

App.ActiveDocument.recompute()
Part.show(testfixture)
Gui.activeDocument().activeView().viewAxometric()
Gui.SendMsgToActiveView("ViewFit")

	#move the part
		# I was going to create everything offset.
		# It seems much simpler to create it all and then move it.
		# That's how all the examples are done. When in Rome....

#example from FreeCAD website. this example doesn't actually work....
#import FreeCAD
#from Draft import *
#myrect = makeRectangle(4,3)
#mydistance = FreeCAD.Vector(2,2,0)
#move(myrect,mydistance)

#This works!
#>>> test = Part.makeBox(1,1,1)
#>>> Part.show(test)
#>>> test2 = Part.makeBox(1,1,1)
#>>> test2.translate(FreeCAD.Vector(5,5,0))

#show it on the screen. Think this is done by the recompute.

#save it







#cleaned up...
#import FreeCAD, Part, Draft
#doc=App.newDocument()
#MDF = 19.05
#radius = 1
#lengthx = 10
#widthy = 10
#height = MDF
#offset = FreeCAD.Vector(10,0,0)
#testfixture = Part.makeBox(lengthx,widthy,MDF)
#hole=Part.makeCylinder(radius,MDF,FreeCAD.Vector(5,5,0))
#testfixture = testfixture.cut(hole)
#testfixture.translate(FreeCAD.Vector(5,0,0))
#App.ActiveDocument.recompute()
#Part.show(testfixture)
#Gui.activeDocument().activeView().viewAxometric()
#Gui.SendMsgToActiveView("ViewFit")













